# Questions 

1. Load in the dataset (`starbucks_drinkMenu_expanded.csv`), calling it `drinks_content`, and then briefly explore it, printing out: first 5 rows, last 5 rows, and then all of the data. Find out the dimensions of the data (number of rows and columns) and the column names.

2. We're going to be looking at the number of `Calories` in each drink.
Calculate some quick summary statistics (e.g. the mean, the maximum and minimum). 

3. Select the variables `Beverage_category`, `Beverage`, `Beverage prep` and `Calories` from the `drinks_content` data frame, and assign the selected columns to a new data frame called `drinks`. Check if there are any missing  values anywhere in the data, and drop any rows containing them if there are.

4. In your `drinks` dataframe create a new variable (column) called `calorie_diff`, which stores the difference between 135 calories (135 calories = 10 cubes of sugar!) and the calories in each drink. (Hint: you’ll want to subtract the calories from 135 to see which drink have more or less than 10 cups of sugar).

5. Summarise the mean number of calories in each beverage category.

6. **Harder** - Which `Beverage_prep` type contains more than the average calories of all drinks?
(Hint: to answer this, you’ll have to first figure out what the average calories across all drinks are, and then use that as a filter for the grouped Beverage_prep data).

7. **Harder**  - Which is the best type of **coffee drink** to get if you’re worried about consuming too many calories?  (Hint: you can use pd.unique() on a column to get all unique values/levels of that column! Also remember that you can use isin() to subset with a list)

8. Filter the dataset drinks so we only take "Classic Espresso Drinks", and save this in a new data frame called `espresso_drinks`.

9. Group your `espresso_drinks` data frame by the type of `Beverage prep`, and then find out the mean calories for each drink group.

10. Get the same grouped mean `Calories` values as above, but this time sorted in descending order. (Hint: so you're able to sort the resulting groupby by the 'Calories' column you will want to ensure you get back a dataframe and not a series)

# Extension

Now, play around with the data yourself. Is there anything in the data? Any interesting plots you can make?

In [1]:
import pandas as pd

In [2]:
# Q1 
drinks_content = pd.read_csv("starbucks_drinkMenu_expanded.csv")

In [4]:
drinks_content.head(5)

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [6]:
drinks_content.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Beverage_category          242 non-null    object
 1   Beverage                   242 non-null    object
 2   Beverage_prep              242 non-null    object
 3   Calories                   242 non-null    int64
 4    Total Fat (g)             242 non-null    object
 5   Trans Fat (g)              242 non-null    float64
 6   Saturated Fat (g)          242 non-null    float64
 7    Sodium (mg)               242 non-null    int64
 8    Total Carbohydrates (g)   242 non-null    int64
 9   Cholesterol (mg)           242 non-null    int64
 10   Dietary Fibre (g)         242 non-null    int64
 11   Sugars (g)                242 non-null    int64
 12   Protein (g)               242 non-null    float64
 13  Vitamin A (% DV)           242 non-null    object
 14  Vitamin C (% DV)           242 non-null    object
 15   Calcium (% DV)            242 non-null    object
 16  Iron (% DV)                242 non-null    object
 17  Caffeine (mg)              241 non-null    object
dtypes: float64(3), int64(6), object(9)
memory usage: 34.2+ KB

In [8]:
# Q2
drinks_content.describe(include = "all")

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
count,242,242,242,242.000000,242,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242.000000,242,242,242,242,241
unique,9,33,13,NaN,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11,10,14,18,36
top,Classic Espresso Drinks,Tazo® Chai Tea Latte,Soymilk,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10%,0%,10%,0%,75
freq,58,12,66,NaN,34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43,188,51,99,37
mean,NaN,NaN,NaN,193.871901,NaN,1.307025,0.037603,6.363636,128.884298,35.991736,0.805785,32.962810,6.978512,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,102.863303,NaN,1.640259,0.071377,8.630257,82.303223,20.795186,1.445944,19.730199,4.871659,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,120.000000,NaN,0.100000,0.000000,0.000000,70.000000,21.000000,0.000000,18.000000,3.000000,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,185.000000,NaN,0.500000,0.000000,5.000000,125.000000,34.000000,0.000000,32.000000,6.000000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,260.000000,NaN,2.000000,0.100000,10.000000,170.000000,50.750000,1.000000,43.750000,10.000000,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,510.000000,NaN,9.000000,0.300000,40.000000,340.000000,90.000000,8.000000,84.000000,20.000000,NaN,NaN,NaN,NaN,NaN

In [13]:
# Q3 
drinks = drinks_content[["Beverage_category", "Beverage", "Beverage_prep", "Calories"]].copy()
drinks.dropna()

,Beverage_category,Beverage,Beverage_prep,Calories
0,Coffee,Brewed Coffee,Short,3
1,Coffee,Brewed Coffee,Tall,4
2,Coffee,Brewed Coffee,Grande,5
3,Coffee,Brewed Coffee,Venti,5
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70
...,...,...,...,...
237,Frappuccino® Blended Crème,Strawberries & Crème (Without Whipped Cream),Soymilk,320
238,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Tall Nonfat Milk,170
239,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Whole Milk,200
240,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Soymilk,180
241,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande Nonfat Milk,240

In [15]:
# Q4 
drinks["calorie_diff"] = drinks.Calories - 135
drinks

,Beverage_category,Beverage,Beverage_prep,Calories,calorie_diff
0,Coffee,Brewed Coffee,Short,3,-132
1,Coffee,Brewed Coffee,Tall,4,-131
2,Coffee,Brewed Coffee,Grande,5,-130
3,Coffee,Brewed Coffee,Venti,5,-130
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,-65
...,...,...,...,...,...
237,Frappuccino® Blended Crème,Strawberries & Crème (Without Whipped Cream),Soymilk,320,185
238,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Tall Nonfat Milk,170,35
239,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Whole Milk,200,65
240,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Soymilk,180,45
241,Frappuccino® Blended Crème,Vanilla Bean (Without Whipped Cream),Grande Nonfat Milk,240,105

In [17]:
# Q5 
drinks.groupby("Beverage_category").mean()

                                     Calories  calorie_diff
Beverage_category
Classic Espresso Drinks            140.172414      5.172414
Coffee                               4.250000   -130.750000
Frappuccino® Blended Coffee        276.944444    141.944444
Frappuccino® Blended Crème         233.076923     98.076923
Frappuccino® Light Blended Coffee  162.500000     27.500000
Shaken Iced Beverages              114.444444    -20.555556
Signature Espresso Drinks          250.000000    115.000000
Smoothies                          282.222222    147.222222
Tazo® Tea Drinks                   177.307692     42.307692

In [19]:
# Q6 
drinks_mean_calories = drinks.Calories.mean()
drinks_mean_calories

193.87190082644628

In [34]:
drinks.groupby("Beverage_prep").mean()

                      Calories  calorie_diff  bev_prep_mean_cal
Beverage_prep
2% Milk             218.000000     83.000000         218.000000
Doppio               10.000000   -125.000000          10.000000
Grande               85.714286    -49.285714          85.714286
Grande Nonfat Milk  209.615385     74.615385         209.615385
Short                37.000000    -98.000000          37.000000
Short Nonfat Milk    99.166667    -35.833333          99.166667
Solo                  5.000000   -130.000000           5.000000
Soymilk             207.272727     72.272727         207.272727
Tall                 63.428571    -71.571429          63.428571
Tall Nonfat Milk    147.826087     12.826087         147.826087
Venti               118.571429    -16.428571         118.571429
Venti Nonfat Milk   260.000000    125.000000         260.000000
Whole Milk          283.750000    148.750000         283.750000

In [50]:
# Q7 
pd.unique(drinks.Beverage_category)

coffee_drinks = drinks.loc[drinks["Beverage_category"].isin(["Coffee", "Classic Espresso Drinks", "Signature Espresso Drinks",
       "Frappuccino® Blended Coffee", "Frappuccino® Light Blended Coffee"])].copy()


coffee_drinks.groupby("Beverage_category")["Calories"].min()

Beverage_category
Classic Espresso Drinks                5
Coffee                                 3
Frappuccino® Blended Coffee          160
Frappuccino® Light Blended Coffee     90
Signature Espresso Drinks            100
Name: Calories, dtype: int64

In [56]:
# Q8 
espresso_drinks = drinks.loc[drinks["Beverage_category"] == "Classic Espresso Drinks"].copy()
espresso_drinks.head(5)

,Beverage_category,Beverage,Beverage_prep,Calories,calorie_diff,bev_prep_mean_cal
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,-65,70
5,Classic Espresso Drinks,Caffè Latte,2% Milk,100,-35,100
6,Classic Espresso Drinks,Caffè Latte,Soymilk,70,-65,70
7,Classic Espresso Drinks,Caffè Latte,Tall Nonfat Milk,100,-35,100
8,Classic Espresso Drinks,Caffè Latte,2% Milk,150,15,150

In [60]:
# Q9 
espresso_drinks.groupby("Beverage_prep")["Calories"].mean()

Beverage_prep
2% Milk               184.375
Doppio                 10.000
Grande                 15.000
Grande Nonfat Milk    150.000
Short                   5.000
Short Nonfat Milk      78.000
Solo                    5.000
Soymilk               151.250
Tall                   10.000
Tall Nonfat Milk      116.000
Venti                  25.000
Venti Nonfat Milk     194.000
Name: Calories, dtype: float64

In [63]:
# Q10
espresso_drinks.groupby("Beverage_prep")["Calories"].mean().reset_index(name = "mean_claories")

         Beverage_prep  mean_claories
0              2% Milk        184.375
1               Doppio         10.000
2               Grande         15.000
3   Grande Nonfat Milk        150.000
4                Short          5.000
5    Short Nonfat Milk         78.000
6                 Solo          5.000
7              Soymilk        151.250
8                 Tall         10.000
9     Tall Nonfat Milk        116.000
10               Venti         25.000
11   Venti Nonfat Milk        194.000